version: '3.7'
services:

  http-proxy:
    image: wcogtas/http-proxy:1.0.0
    container_name: http-proxy
    build: 
      context: ./gtas-parent
      dockerfile: docker-resources/proxy.Dockerfile
    restart: always
    ports:
      - 443:443
      - 80:80
    networks:
      - GTAS-webapp-network
    secrets:
      - elastic-bootstrap-password
      - source: webapp-cert
        target: /wcogtas.org.crt
      - source: webapp-key
        target: /wcogtas.org.key

  web-app:
    image: wcogtas/web-app:1.0.0
    container_name: web-app
    build: 
      context: ./gtas-parent
      dockerfile: web-app.Dockerfile
    ports:
      - 8080:8080
      - 8443:8443
    environment: 
      - DB_HOST=mariadb
      - KIBANA_HOST=kibana
      - NEO4J_HOST=neo4j
      - ACTIVEMQ_HOST=activemq
      - PROXY_HOST=httpproxy
      - ELASTICSEARCH=elasticsearch
    networks:
      - GTAS-webapp-network
    restart: always
    secrets:
     - mysql-webapp-user
     - mysql-webapp-password
     - webapp-neo4j-user
     - webapp-neo4j-password
     - elastic-bootstrap-password
     - source: webapp-cert
       target: /usr/local/tomcat/conf/wcogtas.org.crt
     - source: webapp-key
       target: /usr/local/tomcat/conf/wcogtas.org.key
     - source: elastic-cert
       target: /usr/local/tomcat/conf/elasticsearch-node1.crt
     - source: elastic-key
       target: /usr/local/tomcat/conf/elasticsearch-node1.key
     - source: elastic-ca
       target: /usr/local/tomcat/conf/elastic-ca.crt
    volumes:
      - m2:/root/.m2
      - scheduler-logs:/scheduler-logs

  gtas-scheduler:
    image: wcogtas/gtas-scheduler:1.0.0
    container_name: gtas-scheduler
    build: 
      context: .
      dockerfile: ./gtas-parent/gtas-job-scheduler-war/gtas-scheduler.Dockerfile
    restart: always
    environment:
      DB_HOST: mariadb
      KIBANA_HOST: kibana
      NEO4J_HOST: neo4j
      ACTIVEMQ_HOST: activemq
    volumes:
      - scheduler-logs:/usr/local/tomcat/logs
    secrets:
      - mysql-processor-user
      - mysql-processor-password
      - webapp-neo4j-user
      - webapp-neo4j-password
    networks:
      - GTAS-webapp-network
    depends_on: 
      - activemq

  activemq:
    image: rmohr/activemq:5.15.9
    container_name: activemq
    restart: always
    networks: 
      - GTAS-webapp-network

  mariadb:
    image: wcogtas/mariadb:1.0.0
    build:
      context: ./gtas-parent
      dockerfile: mariadb.Dockerfile
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql-root-password
    secrets:
     - mysql-etl-user
     - mysql-etl-password
     - mysql-processor-user
     - mysql-processor-password
     - mysql-webapp-user
     - mysql-webapp-password
     - mysql-healthcheck-user
     - mysql-healthcheck-password
     - mysql-logstash-user
     - mysql-logstash-password
     - mysql-root-password
    ports:
      - 3306:3306
    networks:
      - GTAS-webapp-network
    restart: always
    volumes:
      - db-data:/var/lib/mysql


secrets:
  mysql-etl-user:
    file: ./gtas-parent/gtas-commons/secrets/mysql_etl_user.txt
  mysql-etl-password:
    file: ./gtas-parent/gtas-commons/secrets/mysql_etl_password.txt
  mysql-healthcheck-user:
    file: ./gtas-parent/gtas-commons/secrets/mysql_healthcheck_user.txt
  mysql-healthcheck-password:
    file: ./gtas-parent/gtas-commons/secrets/mysql_healthcheck_password.txt
  mysql-logstash-user:
    file: ./gtas-parent/gtas-commons/secrets/mysql_logstash_user.txt
  mysql-logstash-password:
    file: ./gtas-parent/gtas-commons/secrets/mysql_logstash_password.txt
  elastic-bootstrap-password:
    file: ./gtas-parent/gtas-commons/secrets/elastic_bootstrap_password.txt
  mysql-processor-user:
    file: ./gtas-parent/gtas-commons/secrets/mysql_processor_user.txt
  mysql-processor-password:
    file: ./gtas-parent/gtas-commons/secrets/mysql_processor_password.txt
  mysql-webapp-user:
    file: ./gtas-parent/gtas-commons/secrets/mysql_webapp_user.txt
  mysql-webapp-password:
    file: ./gtas-parent/gtas-commons/secrets/mysql_webapp_password.txt
  mysql-root-password:
    file: ./gtas-parent/gtas-commons/secrets/mysql_root_password.txt
  webapp-neo4j-user:
    file: ./gtas-parent/gtas-commons/secrets/webapp_neo4j_user.txt
  webapp-neo4j-password:
    file: ./gtas-parent/gtas-commons/secrets/webapp_neo4j_password.txt
  elastic-key:
    file: ./gtas-parent/gtas-commons/secrets/elasticsearch-node1.key
  elastic-ca:
    file: ./gtas-parent/gtas-commons/secrets/elastic-ca.crt
  elastic-cert:
    file: ./gtas-parent/gtas-commons/secrets/elasticsearch-node1.crt
  webapp-cert:
    file: ./gtas-parent/gtas-commons/secrets/wcogtas.org.crt
  webapp-key:
    file: ./gtas-parent/gtas-commons/secrets/wcogtas.org.key

volumes:
  db-data:
  m2:
  scheduler-logs:

networks:
  GTAS-webapp-network:
    attachable: true