version: "3.7"

services:

  kibana:
    container_name: kibana
    image: wcogtas/kibana:1.0.0
    build:
      context: ./gtas-parent/scripts/elastic
      dockerfile: install/docker/kibana/kibana.Dockerfile
    environment:
      ELASTICSEARCH_HOSTS: https://elasticsearch:9200
    ports:
      - 5601:5601
    restart: always
    volumes:
      - kibana-conf:/usr/share/kibana/data
    networks:
      - GTAS-webapp-network
    secrets:
      - source: elasticsearch-ca
        target: /etc/kibana/config/ca.crt
      - source: kibana-crt
        target: /etc/kibana/config/kibana.crt
      - source: kibana-key
        target: /etc/kibana/config/kibana.key
    depends_on:
      - elasticsearch

  elasticsearch:
    image: wcogtas/elasticsearch:1.0.0
    container_name: elasticsearch
    build:
      context: ./gtas-parent/scripts/elastic
      dockerfile: install/docker/elasticsearch/elasticsearch.Dockerfile
    ports:
      - 9300:9300
      - 9200:9200
    restart: always
    volumes: 
      - es-data:/usr/share/elasticsearch/data
      - elasticsearch-conf:/usr/share/elasticsearch/config/
    networks: 
      - GTAS-webapp-network
    secrets:
      - source: elasticsearch-ca
        target: /usr/share/elasticsearch/config/certs/elasticsearch/elastic-ca.crt
      - source: elasticsearch-instance-crt
        target: /usr/share/elasticsearch/config/certs/elasticsearch/elasticsearch-node1.crt
      - source: elasticsearch-instance-key
        target: /usr/share/elasticsearch/config/certs/elasticsearch/elasticsearch-node1.key

  logstash:
    image: wcogtas/logstash:1.0.0
    container_name: logstash
    build:
      context: ./gtas-parent/scripts/elastic
      dockerfile: ./install/docker/logstash/logstash.Dockerfile
    environment: 
      MARIADB_HOST: 'mariadb'
      ELASTIC_HOST: 'https://elasticsearch'
      XPACK_MONITORING_ELASTICSEARCH_HOSTS: 'elasticsearch'
      LOGSTASH_KEYSTORE_PASS: admin123
    restart: always
    secrets:
      - elasticsearch-ca
    networks:
      - GTAS-webapp-network
    volumes:
      - logstash-conf:/usr/share/logstash/config/
    depends_on:
      - elasticsearch

  elk-setup:
    image: wcogtas/elk-setup:1.0.0
    container_name: elk-setup
    build:
      context: ./gtas-parent/scripts/elastic
      dockerfile: ./install/docker/elk-setup/elk-setup.Dockerfile
    environment:
      KIBANA_HOST: 'kibana'
      ELASTICSEARCH_HOST: 'elasticsearch'
    volumes:
      - logstash-conf:/logstash-conf
      - kibana-conf:/kibana-conf
      - elasticsearch-conf:/elasticsearch-conf
    secrets:
      - logstash-keystore-password
      - mysql-logstash-user
      - mysql-logstash-password
      - elastic-password
      - elasticsearch-kibana-user
      - elasticsearch-kibana-password
      - elastic-bootstrap-password
    networks:
      - GTAS-webapp-network


secrets:
  logstash-keystore-password:
    file: ./gtas-parent/gtas-commons/secrets/logstash_keystore_password.txt
  mysql-logstash-user:
    file: ./gtas-parent/gtas-commons/secrets/mysql_logstash_user.txt
  mysql-logstash-password:
    file: ./gtas-parent/gtas-commons/secrets/mysql_logstash_password.txt
  elastic-password:
    file: ./gtas-parent/gtas-commons/secrets/elastic_password.txt
  elasticsearch-kibana-user:
    file: ./gtas-parent/gtas-commons/secrets/elasticsearch_kibana_user.txt
  elasticsearch-kibana-password:
    file: ./gtas-parent/gtas-commons/secrets/elasticsearch_kibana_password.txt
  elastic-bootstrap-password:
    file: ./gtas-parent/gtas-commons/secrets/elastic_bootstrap_password.txt
  elasticsearch-ca:
    file: ./gtas-parent/gtas-commons/secrets/elastic-ca.crt
  elasticsearch-instance-crt:
    file: ./gtas-parent/gtas-commons/secrets/elasticsearch-node1.crt
  elasticsearch-instance-key:
    file: ./gtas-parent/gtas-commons/secrets/elasticsearch-node1.key
  kibana-crt:
    file: ./gtas-parent/gtas-commons/secrets/kibana.crt
  kibana-key:
    file: ./gtas-parent/gtas-commons/secrets/kibana.key

volumes:
  logstash-conf:
  kibana-conf:
  elasticsearch-conf:
  es-data:

networks:
  GTAS-webapp-network:
    attachable: true