version: "3.7"

services:

  etl-job:
    container_name: etl-job
    image: wcogtas/neo4j-etl-job:1.0.0
    build:
      context: .
      dockerfile: ./gtas-neo4j-etl/etl_job.Dockerfile
    environment:
      NEO4J_HOSTNAME: neo4j
      DB_HOSTNAME: mariadb
    restart: always
    secrets:
      - mysql-etl-user
      - mysql-etl-password
      - etl-neo4j-user
      - etl-neo4j-password
    networks: 
      - gtas-webapp-network
    depends_on: 
      - neo4j

  neo4j:
    container_name: neo4j
    image: wcogtas/neo4j:1.0.0
    build:
      context: .
      dockerfile: ./gtas-neo4j-etl/neo4j.Dockerfile
    restart: always
    volumes:
       - neo4j-data:/data
    ports:
      - 7474:7474   
      - 7687:7687
    networks: 
      - gtas-webapp-network

volumes:
   neo4j-data:

networks:
  gtas-webapp-network:
    attachable: true

secrets:
  mysql-etl-user:
    file: ./gtas-parent/gtas-commons/secrets/mysql_etl_user.txt
  mysql-etl-password:
    file: ./gtas-parent/gtas-commons/secrets/mysql_etl_password.txt
  etl-neo4j-user:
    file: ./gtas-parent/gtas-commons/secrets/etl_neo4j_user.txt
  etl-neo4j-password:
    file: ./gtas-parent/gtas-commons/secrets/etl_neo4j_password.txt