name: Pipeline workflow
on: push
jobs:
  build:
    name: webapp
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: simbam1/webapp
          path: ./gtas-parent
          dockerfile: ./gtas-parent/web-app.Dockerfile
          tags: latest
