name: Pipeline workflow
on: push
jobs:
  build:
    name: webapp
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: simbam1/webapp
          path: ./gtas-parent
          dockerfile: ./gtas-parent/web-app.Dockerfile
          tags: latest
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: eksctl-cmd
        uses: robatwave/github-action-eksctl@0.1.2
        with:
          args: create cluster --name dev-testing  --region us-east-1

      # - name: Trigger deploy
      #   uses: Consensys/kubernetes-action@master
      #   with:
      #     args: get svc # apply -f deployment.yaml 
