name: Pipeline workflow
on: push
jobs:
  build:
    name: webapp
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      # - uses: docker/build-push-action@v1
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
      #     repository: simbam1/webapp
      #     path: ./gtas-parent
      #     dockerfile: ./gtas-parent/web-app.Dockerfile
      #     tags: latest  
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - uses: prepor/action-aws-iam-authenticator@master
      # - name: eksctl-cmd
      #   uses: robatwave/github-action-eksctl@0.1.2
      #   with:
      #     args: create cluster dev-test-six
      - run: |
          sudo apt-get -y update
          sudo apt-get install -y curl
          curl -L https://github.com/kubernetes/kompose/releases/download/v1.21.0/kompose-linux-amd64 -o kompose
          chmod +x kompose
          sudo mv ./kompose /usr/local/bin/kompose
          kompose convert --out deploy.yaml
      # - uses: azure/k8s-bake@v1
      #   with:
      #     renderEngine: 'kompose'
      #     dockerComposeFile: './docker-compose.yml'
      #     kompose-version: 'latest'     
      - run: ls  
      - name: Trigger deploy
        uses: Consensys/kubernetes-action@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: apply  --v=10 -f deploy.yaml
