name: Pipeline workflow
on: push
jobs:
  build:
    name: webapp
    runs-on: 19.04
    steps:
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: simbam1/webapp
        tags: latest
        tag_with_ref: true
        tag_with_sha: true

